language: c

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: Z4XxLt0tdRYnuRNgW63dOC5tssA8f5By+vqFVruNhFa5bd15OlSJ2eGIVaK0yjep70/Sfgv/gDIwrsaHZhKaFrY+rV62VE82qQKc/QoGkJ8MPX5vALmMAZKbE0j7d21ZvxXvcki8WNk70WpRW+A8EGPgCN1v2yAhjufpddleD8A=

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-cran-devtools
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check ${R_PKG}_*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - set -e
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"

after_failure:
  - cd ..; for i in `ls *.Rcheck/00*`; do cat $i; done
